exports = {
	guard: {
		width: 20,
		height: 50,
		offsetX: -10,
		offsetY: -50,
		images: [
			'resources/images/layer1a/guardDownWalk01.png',
			'resources/images/layer1a/guardDownWalk02.png',
			'resources/images/layer1a/guardDownWalk03.png',
			'resources/images/layer1a/guardDownWalk04.png',
			'resources/images/layer1a/guardDownWalk05.png',
			'resources/images/layer1a/guardDownWalk06.png',
			'resources/images/layer1a/guardDownWalk07.png',
			'resources/images/layer1a/guardDownWalk08.png',
			'resources/images/layer1a/guardDownWalk09.png',
			'resources/images/layer1a/guardDownWalk10.png',
			'resources/images/layer1a/guardDownWalk11.png',
			'resources/images/layer1a/guardDownWalk12.png',
			'resources/images/layer1a/guardDownWalk13.png',
			'resources/images/layer1a/guardDownWalk14.png',
			'resources/images/layer1a/guardDownWalk15.png',
			'resources/images/layer1a/guardDownWalk16.png',
			'resources/images/layer1a/guardDownWalk17.png',
			'resources/images/layer1a/guardDownWalk18.png',
			'resources/images/layer1a/guardDownWalk19.png',
			'resources/images/layer1a/guardDownWalk20.png',
			'resources/images/layer1a/guardUpWalk01.png',
			'resources/images/layer1a/guardUpWalk02.png',
			'resources/images/layer1a/guardUpWalk03.png',
			'resources/images/layer1a/guardUpWalk04.png',
			'resources/images/layer1a/guardUpWalk05.png',
			'resources/images/layer1a/guardUpWalk06.png',
			'resources/images/layer1a/guardUpWalk07.png',
			'resources/images/layer1a/guardUpWalk08.png',
			'resources/images/layer1a/guardUpWalk09.png',
			'resources/images/layer1a/guardUpWalk10.png',
			'resources/images/layer1a/guardUpWalk11.png',
			'resources/images/layer1a/guardUpWalk12.png',
			'resources/images/layer1a/guardUpWalk13.png',
			'resources/images/layer1a/guardUpWalk14.png',
			'resources/images/layer1a/guardUpWalk15.png',
			'resources/images/layer1a/guardUpWalk16.png',
			'resources/images/layer1a/guardUpWalk17.png',
			'resources/images/layer1a/guardUpWalk18.png',
			'resources/images/layer1a/guardUpWalk19.png',
			'resources/images/layer1a/guardUpWalk20.png'
		]
	},
	fireman: {
		width: 20,
		height: 50,
		offsetX: -10,
		offsetY: -50,
		images: [
			'resources/images/layer1a/firemanDownWalk01.png',
			'resources/images/layer1a/firemanDownWalk02.png',
			'resources/images/layer1a/firemanDownWalk03.png',
			'resources/images/layer1a/firemanDownWalk04.png',
			'resources/images/layer1a/firemanDownWalk05.png',
			'resources/images/layer1a/firemanDownWalk06.png',
			'resources/images/layer1a/firemanDownWalk07.png',
			'resources/images/layer1a/firemanDownWalk08.png',
			'resources/images/layer1a/firemanDownWalk09.png',
			'resources/images/layer1a/firemanDownWalk10.png',
			'resources/images/layer1a/firemanDownWalk11.png',
			'resources/images/layer1a/firemanDownWalk12.png',
			'resources/images/layer1a/firemanDownWalk13.png',
			'resources/images/layer1a/firemanDownWalk14.png',
			'resources/images/layer1a/firemanDownWalk15.png',
			'resources/images/layer1a/firemanDownWalk16.png',
			'resources/images/layer1a/firemanDownWalk17.png',
			'resources/images/layer1a/firemanDownWalk18.png',
			'resources/images/layer1a/firemanDownWalk19.png',
			'resources/images/layer1a/firemanDownWalk20.png',
			'resources/images/layer1a/firemanUpWalk01.png',
			'resources/images/layer1a/firemanUpWalk02.png',
			'resources/images/layer1a/firemanUpWalk03.png',
			'resources/images/layer1a/firemanUpWalk04.png',
			'resources/images/layer1a/firemanUpWalk05.png',
			'resources/images/layer1a/firemanUpWalk06.png',
			'resources/images/layer1a/firemanUpWalk07.png',
			'resources/images/layer1a/firemanUpWalk08.png',
			'resources/images/layer1a/firemanUpWalk09.png',
			'resources/images/layer1a/firemanUpWalk10.png',
			'resources/images/layer1a/firemanUpWalk11.png',
			'resources/images/layer1a/firemanUpWalk12.png',
			'resources/images/layer1a/firemanUpWalk13.png',
			'resources/images/layer1a/firemanUpWalk14.png',
			'resources/images/layer1a/firemanUpWalk15.png',
			'resources/images/layer1a/firemanUpWalk16.png',
			'resources/images/layer1a/firemanUpWalk17.png',
			'resources/images/layer1a/firemanUpWalk18.png',
			'resources/images/layer1a/firemanUpWalk19.png',
			'resources/images/layer1a/firemanUpWalk20.png'
		]
	},
	trader: {
		width: 20,
		height: 50,
		offsetX: -10,
		offsetY: -50,
		images: [
			'resources/images/layer1a/traderDownWalk01.png',
			'resources/images/layer1a/traderDownWalk02.png',
			'resources/images/layer1a/traderDownWalk03.png',
			'resources/images/layer1a/traderDownWalk04.png',
			'resources/images/layer1a/traderDownWalk05.png',
			'resources/images/layer1a/traderDownWalk06.png',
			'resources/images/layer1a/traderDownWalk07.png',
			'resources/images/layer1a/traderDownWalk08.png',
			'resources/images/layer1a/traderDownWalk09.png',
			'resources/images/layer1a/traderDownWalk10.png',
			'resources/images/layer1a/traderDownWalk11.png',
			'resources/images/layer1a/traderDownWalk12.png',
			'resources/images/layer1a/traderDownWalk13.png',
			'resources/images/layer1a/traderDownWalk14.png',
			'resources/images/layer1a/traderDownWalk15.png',
			'resources/images/layer1a/traderDownWalk16.png',
			'resources/images/layer1a/traderDownWalk17.png',
			'resources/images/layer1a/traderDownWalk18.png',
			'resources/images/layer1a/traderDownWalk19.png',
			'resources/images/layer1a/traderDownWalk20.png',
			'resources/images/layer1a/traderUpWalk01.png',
			'resources/images/layer1a/traderUpWalk02.png',
			'resources/images/layer1a/traderUpWalk03.png',
			'resources/images/layer1a/traderUpWalk04.png',
			'resources/images/layer1a/traderUpWalk05.png',
			'resources/images/layer1a/traderUpWalk06.png',
			'resources/images/layer1a/traderUpWalk07.png',
			'resources/images/layer1a/traderUpWalk08.png',
			'resources/images/layer1a/traderUpWalk09.png',
			'resources/images/layer1a/traderUpWalk10.png',
			'resources/images/layer1a/traderUpWalk11.png',
			'resources/images/layer1a/traderUpWalk12.png',
			'resources/images/layer1a/traderUpWalk13.png',
			'resources/images/layer1a/traderUpWalk14.png',
			'resources/images/layer1a/traderUpWalk15.png',
			'resources/images/layer1a/traderUpWalk16.png',
			'resources/images/layer1a/traderUpWalk17.png',
			'resources/images/layer1a/traderUpWalk18.png',
			'resources/images/layer1a/traderUpWalk19.png',
			'resources/images/layer1a/traderUpWalk20.png'
		]
	},
	engineer: {
		width: 20,
		height: 50,
		offsetX: -10,
		offsetY: -50,
		images: [
			'resources/images/layer1a/engineerDownWalk01.png',
			'resources/images/layer1a/engineerDownWalk02.png',
			'resources/images/layer1a/engineerDownWalk03.png',
			'resources/images/layer1a/engineerDownWalk04.png',
			'resources/images/layer1a/engineerDownWalk05.png',
			'resources/images/layer1a/engineerDownWalk06.png',
			'resources/images/layer1a/engineerDownWalk07.png',
			'resources/images/layer1a/engineerDownWalk08.png',
			'resources/images/layer1a/engineerDownWalk09.png',
			'resources/images/layer1a/engineerDownWalk10.png',
			'resources/images/layer1a/engineerDownWalk11.png',
			'resources/images/layer1a/engineerDownWalk12.png',
			'resources/images/layer1a/engineerDownWalk13.png',
			'resources/images/layer1a/engineerDownWalk14.png',
			'resources/images/layer1a/engineerDownWalk15.png',
			'resources/images/layer1a/engineerDownWalk16.png',
			'resources/images/layer1a/engineerDownWalk17.png',
			'resources/images/layer1a/engineerDownWalk18.png',
			'resources/images/layer1a/engineerDownWalk19.png',
			'resources/images/layer1a/engineerDownWalk20.png',
			'resources/images/layer1a/engineerUpWalk01.png',
			'resources/images/layer1a/engineerUpWalk02.png',
			'resources/images/layer1a/engineerUpWalk03.png',
			'resources/images/layer1a/engineerUpWalk04.png',
			'resources/images/layer1a/engineerUpWalk05.png',
			'resources/images/layer1a/engineerUpWalk06.png',
			'resources/images/layer1a/engineerUpWalk07.png',
			'resources/images/layer1a/engineerUpWalk08.png',
			'resources/images/layer1a/engineerUpWalk09.png',
			'resources/images/layer1a/engineerUpWalk10.png',
			'resources/images/layer1a/engineerUpWalk11.png',
			'resources/images/layer1a/engineerUpWalk12.png',
			'resources/images/layer1a/engineerUpWalk13.png',
			'resources/images/layer1a/engineerUpWalk14.png',
			'resources/images/layer1a/engineerUpWalk15.png',
			'resources/images/layer1a/engineerUpWalk16.png',
			'resources/images/layer1a/engineerUpWalk17.png',
			'resources/images/layer1a/engineerUpWalk18.png',
			'resources/images/layer1a/engineerUpWalk19.png',
			'resources/images/layer1a/engineerUpWalk20.png'
		]
	},
	citizen: {
		width: 20,
		height: 50,
		offsetX: -10,
		offsetY: -50,
		images: [
			'resources/images/layer1a/manDownWalk01.png',
			'resources/images/layer1a/manDownWalk02.png',
			'resources/images/layer1a/manDownWalk03.png',
			'resources/images/layer1a/manDownWalk04.png',
			'resources/images/layer1a/manDownWalk05.png',
			'resources/images/layer1a/manDownWalk06.png',
			'resources/images/layer1a/manDownWalk07.png',
			'resources/images/layer1a/manDownWalk08.png',
			'resources/images/layer1a/manDownWalk09.png',
			'resources/images/layer1a/manDownWalk10.png',
			'resources/images/layer1a/manDownWalk11.png',
			'resources/images/layer1a/manDownWalk12.png',
			'resources/images/layer1a/manDownWalk13.png',
			'resources/images/layer1a/manDownWalk14.png',
			'resources/images/layer1a/manDownWalk15.png',
			'resources/images/layer1a/manDownWalk16.png',
			'resources/images/layer1a/manDownWalk17.png',
			'resources/images/layer1a/manDownWalk18.png',
			'resources/images/layer1a/manDownWalk19.png',
			'resources/images/layer1a/manDownWalk20.png',
			'resources/images/layer1a/manUpWalk01.png',
			'resources/images/layer1a/manUpWalk02.png',
			'resources/images/layer1a/manUpWalk03.png',
			'resources/images/layer1a/manUpWalk04.png',
			'resources/images/layer1a/manUpWalk05.png',
			'resources/images/layer1a/manUpWalk06.png',
			'resources/images/layer1a/manUpWalk07.png',
			'resources/images/layer1a/manUpWalk08.png',
			'resources/images/layer1a/manUpWalk09.png',
			'resources/images/layer1a/manUpWalk10.png',
			'resources/images/layer1a/manUpWalk11.png',
			'resources/images/layer1a/manUpWalk12.png',
			'resources/images/layer1a/manUpWalk13.png',
			'resources/images/layer1a/manUpWalk14.png',
			'resources/images/layer1a/manUpWalk15.png',
			'resources/images/layer1a/manUpWalk16.png',
			'resources/images/layer1a/manUpWalk17.png',
			'resources/images/layer1a/manUpWalk18.png',
			'resources/images/layer1a/manUpWalk19.png',
			'resources/images/layer1a/manUpWalk20.png'
		]
	}
};